/**
 * generated by Xtext 2.11.0
 */
package org.learning.example.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compilation Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.learning.example.myDsl.CompilationUnit#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.learning.example.myDsl.MyDslPackage#getCompilationUnit()
 * @model
 * @generated
 */
public interface CompilationUnit extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference list.
   * The list contents are of type {@link org.learning.example.myDsl.TypeDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference list.
   * @see org.learning.example.myDsl.MyDslPackage#getCompilationUnit_Type()
   * @model containment="true"
   * @generated
   */
  EList<TypeDeclaration> getType();

} // CompilationUnit
