/**
 * generated by Xtext 2.11.0
 */
package org.learning.example.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.learning.example.myDsl.TypeDeclaration#getKind <em>Kind</em>}</li>
 *   <li>{@link org.learning.example.myDsl.TypeDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link org.learning.example.myDsl.TypeDeclaration#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.learning.example.myDsl.MyDslPackage#getTypeDeclaration()
 * @model
 * @generated
 */
public interface TypeDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * The literals are from the enumeration {@link org.learning.example.myDsl.TypeKinds}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Kind</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see org.learning.example.myDsl.TypeKinds
   * @see #setKind(TypeKinds)
   * @see org.learning.example.myDsl.MyDslPackage#getTypeDeclaration_Kind()
   * @model
   * @generated
   */
  TypeKinds getKind();

  /**
   * Sets the value of the '{@link org.learning.example.myDsl.TypeDeclaration#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see org.learning.example.myDsl.TypeKinds
   * @see #getKind()
   * @generated
   */
  void setKind(TypeKinds value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.learning.example.myDsl.MyDslPackage#getTypeDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.learning.example.myDsl.TypeDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.learning.example.myDsl.NamedElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.learning.example.myDsl.MyDslPackage#getTypeDeclaration_Elements()
   * @model containment="true"
   * @generated
   */
  EList<NamedElement> getElements();

} // TypeDeclaration
