/**
 * generated by Xtext 2.11.0
 */
package org.learning.example.ide;

import org.learning.example.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
