/*
 * generated by Xtext 2.11.0
 */
package org.learning.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.learning.example.ui.internal.ExampleActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ExampleActivator.getInstance().getInjector("org.learning.example.MyDsl");
	}

}
